name: Debug

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  PROPERTIES_FILE: .github/gradle/debug-gradle.properties
  GRADLE_USER_HOME: ~/.gradle

jobs:
  build-debug-apk:
    name: Create Debug APK File
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Gradle Property File
        run: |
          mkdir -p ${GRADLE_USER_HOME}
          mv ${PROPERTIES_FILE} ${GRADLE_USER_HOME}/gradle.properties
          ls -a ${GRADLE_USER_HOME}

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
        
      - name: Assemble APK File
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            clean 
            ktlintCheck 
            lintDebug
            testDebugUnitTest
            assembleDebug --scan

      - name: Release New Version
        uses: softprops/action-gh-release@v1
        with: 
          body: |
            For Debugging purposes only.
            Build Scan URL: ${{ steps.gradle.outputs.build-scan-url }}
          append_body: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/*.apk
            build/reports/
          
          
